In [2]:
import sys
import os

import numpy as np



In [2]:
from radmodel import *

In [4]:
RadiativeModelOld = RadiativeModel

In [9]:
type(RadiativeModelOld)

type

In [5]:
X = np.array([1,2]).reshape(2,1)
X

array([[1],
       [2]])

In [9]:
T_VCS1, T_VCS2 = 40.,100.
VCS1, VCS2 = 1.,2.

B = np.array([[1,.5],[.5,1]])

X = np.array([T_VCS1, T_VCS2]).reshape(2,1) 
Fx = np.array([VCS1, VCS2]).reshape(2,1)
S = np.linalg.solve(B,Fx)
X += S

print(X)
print(S)

[[ 40.]
 [102.]]
[[0.]
 [2.]]
